### ISSUE TITLE
[3pt] Demo local 2 node long-term simulation run

### ISSUE THREAD

**Issue by scasplte2** [Topl/Prosomo#14]
Networking functionality can be demonstrated by interfacing at least two nodes (instances of prosomo) on the local host of a single computer

**Comment by aaronschutza** [comment]
We can now run long term simulations using two nodes on the same local host

**Comment by aaronschutza** [comment]
![image](https://user-images.githubusercontent.com/14355515/77679729-f23f4e00-6f60-11ea-891f-4d736dd8e02f.png)

**Comment by scasplte2** [comment]
With each individual simulation implementing multiple stakeholders as shown
here?
[image: Prosomo simulation diagrams.png]

>

**Comment by scasplte2** [comment]
With each individual simulation implementing multiple stakeholders as shown
here?
![Prosomo simulation diagrams](https://user-images.githubusercontent.com/1753335/77682274-ad1d1b00-6f64-11ea-9745-df3f3da1a59e.png)

**Comment by aaronschutza** [comment]
> With each individual simulation implementing multiple stakeholders as shown
> here?
> ![Prosomo simulation diagrams](https://user-images.githubusercontent.com/1753335/77682274-ad1d1b00-6f64-11ea-9745-df3f3da1a59e.png)

Yes, the setup has holders 0 through 7 on 127.0.0.1 and holders 8 through 15 on 127.0.0.2 each executing in a separate folder.  This is with the delay turned on for messages routed locally (e.g. message from holder 0 to holder 1)

**Comment by aaronschutza** [comment]
The initial time is synchronized across the two instances with a txt file that is generated during staging that has the current system time in milliseconds.

**Comment by aaronschutza** [comment]
![image](https://user-images.githubusercontent.com/14355515/77717403-62c08c00-6fae-11ea-801e-6d660fc688e3.png)

**Comment by aaronschutza** [comment]
![image](https://user-images.githubusercontent.com/14355515/77717633-feea9300-6fae-11ea-85f9-5ba22ee18e4d.png)

**Comment by aaronschutza** [comment]
Simulation is stable across epoch for 86400 slots, time scale set to 0.2 (200ms slots)

**Comment by aaronschutza** [comment]
Run ./ab.sh from project directory to execute 2 node local setup
