### ISSUE TITLE
[5pt] Setup and begin running multi-client hosted simulation

### ISSUE THREAD

**Issue by scasplte2** [Topl/Prosomo#15]
- [x] Investigate containerization to distribute simulation
- [x] Evaluate amount of storage required
- [x] Specify and implement bootstrapping new holders into running simulation spanning multiple epochs

**Comment by aaronschutza** [comment]
Updated bootstrapping
![image](https://user-images.githubusercontent.com/14355515/77984481-49ce1880-72d7-11ea-8e39-0e130ee0050f.png)

**Comment by aaronschutza** [comment]
https://github.com/Topl/Prosomo/commit/b2a0129f6eb56dcb03dbd678779987cfbb1dc54d

**Comment by aaronschutza** [comment]
Bootstrapping new holders works but will take a long time because tines are being built up one block at a time.  I need to fix how tine building triggers.

**Comment by aaronschutza** [comment]
New Release: https://github.com/Topl/Prosomo/releases/tag/0.7

**Comment by aaronschutza** [comment]
Docker packaging is included in sbt native packager, RC1 includes an image that may still need to be configured.  Docker image can be built with 'sbt docker:publishLocal'

**Comment by aaronschutza** [comment]
Under default settings with 8 holders, about 500MB of disk space per 1000 slots of simulation time is used.

**Comment by aaronschutza** [comment]
Bitcoin p2p guide: https://bitcoin.org/en/p2p-network-guide#introduction
