### ISSUE TITLE
Long term simulation stability

### ISSUE THREAD

**Issue by aaronschutza** [Topl/Prosomo#19]
We have just begun to execute simulations with real epochs of 24 hours.  Issues related to crashes, stability, and performance will be logged here.

**Comment by aaronschutza** [comment]
24 hour epoch updated in about 4 seconds with nonce buffer
![Screenshot_20200317_170249](https://user-images.githubusercontent.com/14355515/76910400-e1fde380-687b-11ea-8d0d-58ddaf17238f.png)

**Comment by aaronschutza** [comment]
![Screenshot_20200317_181652](https://user-images.githubusercontent.com/14355515/76910461-0bb70a80-687c-11ea-8389-ede4c182521d.png)

**Comment by scasplte2** [comment]
That heap usage looks great! Also surprised that the number of thread >10k. Seems like the tuning has really paid off 👍

**Comment by aaronschutza** [comment]
![Screenshot_2020-03-23_14-14-38](https://user-images.githubusercontent.com/14355515/77355306-3b4d9300-6d12-11ea-9a74-6307c1d9ec14.png)

**Comment by aaronschutza** [comment]
Simulation ran for a few epochs until wifi gave out and interrupted ssh.

**Comment by aaronschutza** [comment]
Simulation is now stable with current jvm options and levelDB database refresh interval, bottle neck is now disk space.
