### ISSUE TITLE
[#pt] Clean shutdown of simulation

### ISSUE THREAD

**Issue by scasplte2** [Topl/Prosomo#27]
Related to #12

Exiting the simulation manually should produce no errors and return to the sbt console.  Error handling of actors should be handled correctly upon bugs and crashes.  Stalls and stop commands should preserve database integrity.  Currently if the sbt java runtime is sent a stop signal the database lock is not saved correctly and it prevents loading of database files at the next runtime.

**Comment by aaronschutza** [comment]
The app runtime has been revamped and now cleanly shuts down with ctrl c in headless mode or by closing the UI window.
