### ISSUE TITLE
[8pt] Research needed changes to Prosomo data structure

### ISSUE THREAD

**Issue by scasplte2** [Topl/Prosomo#3]
- [x] changing of arrays to proper classes
- [x] best approach to breaking out the stakeholder, coordinator, router classes
- [x] debugging chain selection with new classes and methods for chain and history

**Comment by aaronschutza** [comment]
Data structures have been specified for most message passing between stakeholders eliminating the need for cumbersome pattern matching on every message.  Boxes now serve as message authentication as well has ledger hash verification.  Each box has a hash of the associated message with a session id and signature corresponding to the message sender.  Ledgers are authenticated by hashing the sequence of transaction or genesis entries and committing that hash to a box upon forging.  Block body and header are now treated separately in all parts of the code.

**Comment by aaronschutza** [comment]
Still need to update state to be a proper class.  Mempool could use the same treatment.
