### ISSUE TITLE
[3pt] Stable Prosomo testnet running with GCP bootstrap

### ISSUE THREAD

**Issue by scasplte2** [Topl/Prosomo#33]
We are experimenting with multiple nodes communicating with a bootstrap server, and debugging bootstrapping procedure and synchronization.

**Comment by aaronschutza** [comment]
Synchronization isn't working correctly, the global time offset isn't being calculated correctly.

**Comment by aaronschutza** [comment]
RC3 is now out and has a new initial time.  At least one genesis forger must be active at all times to prevent empty epochs.
