### ISSUE TITLE
[3pt] Testnet User Interface (Part II)

### ISSUE THREAD

**Issue by aaronschutza** [Topl/Prosomo#49]
This will track progress towards a secure key creation and management window as part of the user interface initiative #47

**Comment by aaronschutza** [comment]
Key creation will progress in the following fashion:

 - User will have a key creation dialog box that will take as an input a BIP39 phrase
 - Option to generate random new BIP39 phrase, show user, and seed the SIG keys with it
 - VRF key will be generated from an unrecorded UUID seed
 - KES key will be generated from an unrecorded UUID seed with the key offset set to the global slot provided by the coordinator
 - Stakeholder actor will be instantiated with the newly generated keys and start trying to forge
 - The default user configuration will be only one stakeholder actor per node emulating a testnet client node to node setup
 - Users will bootstrap to a faucet node with many stakholder actors that randomly distributes transactions to newly generated keys that it discovers on the network
 - The faucet node will contain only genesis forgers and no user will be able to forge from genesis, users may not have genesis keys

**Comment by aaronschutza** [comment]
Simulation will start with a Stakeholder that is not forging.  The loaded configuration will be the last known node view.

**Comment by scasplte2** [comment]
is this something I can test now?
