### ISSUE TITLE
[3pt] UPNP not fully functioning

### ISSUE THREAD

**Issue by aaronschutza** [Topl/Prosomo#50]
The following code regarding initialization of UPNP gateway:

  //p2p
  private val upnpGateway: Option[UPnPGateway] = if (settings.network.upnpEnabled) UPnP.getValidGateway(settings.network) else None
  // TODO use available port on gateway instead settings.network.bindAddress.getPort
  upnpGateway.foreach(_.addPort(settings.network.bindAddress.getPort))

It is working but it isn't using the correct port and this leads only one instance per household router to connect.

**Comment by scasplte2** [comment]
@aaronschutza unless I am misunderstanding something it would seem to me like the line 
```
upnpGateway.foreach(_.addPort(settings.network.bindAddress.getPort))
```
is doing exactly what it should be as I see it correctly mapping the port defined in `settings.network.bindAddress` via upnp.

I think I have been able to resolve this issue on the branch `random_upnp` and I made a pull request for it

**Comment by aaronschutza** [comment]
The last linked commit resolved this issue.
