### ISSUE TITLE
[3pt] Multiplatform Release

### ISSUE THREAD

**Issue by aaronschutza** [Topl/Prosomo#52]
Prosomo is ready for the company wide testnet.  Distributing a release that will run with a single click for mac, windows, and linux is the goal for this issue.  I need to configure the jar to be executed with jvm options, it is not possible to specify these inside the jar itself.  There are many options for executable wrappers of java applications for each target platform.

A future goal would be to have a separate release for a headless instance that uses native image.  Native image must compile on the target platform and is system architecture dependent.  The benefit would be no prior configuration of the system environment, but it would be up to the system admin to pick the right release for their platform.

**Comment by aaronschutza** [comment]
This might work:
https://docs.oracle.com/javase/8/docs/technotes/guides/javaws/

**Comment by aaronschutza** [comment]
Or this:
http://launch4j.sourceforge.net/

**Comment by aaronschutza** [comment]
And this:
http://jsmooth.sourceforge.net/

**Comment by aaronschutza** [comment]
Our only option for now is to run a bat file or shell script to start the application with the desired memory settings.  There doesn't seem to be a straightforward way to package a jar that will behave as an executable on multiple operating systems.

**Comment by aaronschutza** [comment]
Docker best practices:
https://www.youtube.com/watch?v=LJNKYW6Qls0

**Comment by aaronschutza** [comment]
This will likely require a different script for each platform as there is no simple way to deploy jars in a platform independent way while retaining the required memory settings.

**Comment by aaronschutza** [comment]
The desired memory options for all platforms:

-Xms512M
-Xmx2G
-Xss2M
-XX:MaxMetaspaceSize=1024M
-XX:PermSize=512m
-XX:+UseG1GC
-XX:MaxGCPauseMillis=200
-XX:ParallelGCThreads=8
-XX:ConcGCThreads=8
-XX:InitiatingHeapOccupancyPercent=90
-XX:G1HeapRegionSize=2
-Dprosomo

**Comment by scasplte2** [comment]
I think a separate script is also perfectly reasonable if possible given
the difficulty this has presented

**Comment by aaronschutza** [comment]
This actually looks really good:
https://www.ej-technologies.com/products/install4j/overview.html

**Comment by scasplte2** [comment]
oh, yeah. This looks awesome. Is there a trial or should I apply for an
open-source license here
https://www.ej-technologies.com/buy/install4j/openSource/enter  ?

**Comment by aaronschutza** [comment]
Release is now up
https://github.com/Topl/Prosomo/releases/tag/0.7.6
