### ISSUE TITLE
Performance tuning targetting low powered VM instances

### ISSUE THREAD

**Issue by scasplte2** [Topl/Prosomo#68]

**Comment by aaronschutza** [comment]
execution context for each actor can be set in config so they can share threadpools.  Router system can be turned on or off in config.

Single CPU jopts:
-Xms512M -Xmx2G -Xss2M -XX:MaxMetaspaceSize=1024M -XX:PermSize=512m -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:ParallelGCThreads=1 -XX:ConcGCThreads=1 -XX:InitiatingHeapOccupancyPercent=90 -XX:G1HeapRegionSize=2
