### ISSUE TITLE
State Management Operations

### ISSUE THREAD

**Issue by aaronschutza** [Topl/Prosomo#74]
Several operations in the current implementation of Prosomo are not correctly setup for general purpose ledger maintenance.  E.g. Block roll backs are not actually occurring, the state is simply being recovered from StateHistory upon a reorg.  StateHistory is saving a snapshot of state for every block, which is not scalable at all.

We have never pushed Prosomo to a regime where state has increased past a few hundred accounts in size.  There has never been a realistic ledger used with the consensus engine so now is to time to fix these shortcomings.  After this is done Prosomo will become a fully functional consensus platform which will be compatible with different ledger models.

**Comment by aaronschutza** [comment]
Chapter 4 of https://eprint.iacr.org/2017/149.pdf has a very nice review of the Ledger functionality as a global setup.

**Comment by scasplte2** [comment]
Useful documentation on Akka mailboxes
https://doc.akka.io/docs/akka/2.4/scala/mailboxes.html#PriorityMailbox
